import { useState, useCallback } from 'react';
import { AddDoctorFormData } from '@/types/doctor.types';
import { DoctorPrice } from '@/types/serviceType.types';
import { Gender } from '@/enums/common.enums';
import { useDoctorFormHandlers } from './useDoctorFormHandlers';

export interface UseAddDoctorFormProps {
    initialData: AddDoctorFormData;
}

export const useAddDoctorForm = ({ initialData }: UseAddDoctorFormProps) => {
    const [formData, setFormData] = useState<AddDoctorFormData>(initialData);
    const [errors, setErrors] = useState<
        Partial<
            Record<keyof AddDoctorFormData | `servicePrices_${number}_${keyof DoctorPrice}`, string>
        >
    >({});

    // Use shared handlers to reduce duplication
    const {
        handleLanguageToggle,
        handleServicePriceChange,
        addServicePrice,
        removeServicePrice,
        handleFileChange,
    } = useDoctorFormHandlers(setFormData, errors as Record<string, string>, setErrors as any);

    const handleInputChange = useCallback(
        (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
            const { name, value } = e.target;
            setFormData((prev) => ({
                ...prev,
                [name]:
                    name === 'yearsOfExperience'
                        ? Number(value)
                        : name === 'gender'
                          ? value === '' || value === null || value === undefined
                              ? Gender.MALE
                              : Number(value)
                          : value,
            }));
            if (errors[name as keyof typeof errors]) {
                setErrors((prev) => ({ ...prev, [name]: '' }));
            }
        },
        [errors]
    );

    // Validate required fields
    const validateRequiredFields = useCallback(
        (
            errors: Partial<
                Record<
                    keyof AddDoctorFormData | `servicePrices_${number}_${keyof DoctorPrice}`,
                    string
                >
            >
        ) => {
            const requiredFields: (keyof AddDoctorFormData)[] = [
                'fullName',
                'email',
                'bio',
                'positionId',
                'specialtyId',
                // 'password' - removed: will be auto-generated by backend
                // 'confirmPassword' - removed: will be auto-generated by backend
                // 'address' - removed: will be taken from hospitalProfile
                // 'hospitalId' - removed: will be taken from hospitalProfile
            ];

            for (const field of requiredFields) {
                if (!formData[field]) {
                    errors[field as keyof typeof errors] = 'Trường này là bắt buộc';
                }
            }

            // Validate gender separately (check for null/undefined since 0 is valid - Gender.MALE)
            if (formData.gender === null || formData.gender === undefined) {
                errors.gender = 'Trường này là bắt buộc';
            }
        },
        [formData]
    );

    // Validate service prices
    const validateServicePrices = useCallback(
        (
            errors: Partial<
                Record<
                    keyof AddDoctorFormData | `servicePrices_${number}_${keyof DoctorPrice}`,
                    string
                >
            >
        ) => {
            if (formData.servicePrices.length === 0) {
                errors.servicePrices = 'Vui lòng thêm ít nhất một loại dịch vụ';
                return;
            }

            // Check for duplicate service types
            const serviceTypeIds = formData.servicePrices
                .map((price) => price.serviceTypeId)
                .filter((id) => id);
            const duplicateServiceTypes = new Set(
                serviceTypeIds.filter((id, index) => serviceTypeIds.indexOf(id) !== index)
            );

            for (let index = 0; index < formData.servicePrices.length; index++) {
                const price = formData.servicePrices[index];
                if (!price.serviceTypeId) {
                    errors[`servicePrices_${index}_amount`] = 'Vui lòng chọn loại dịch vụ';
                } else if (duplicateServiceTypes.has(price.serviceTypeId)) {
                    errors[`servicePrices_${index}_amount`] =
                        'Loại dịch vụ này đã được chọn. Mỗi bác sĩ chỉ được có một giá cho mỗi loại dịch vụ';
                }
                if (price.amount <= 0) {
                    errors[`servicePrices_${index}_amount`] = 'Giá phải lớn hơn 0';
                }
            }
        },
        [formData.servicePrices]
    );

    const validateForm = useCallback((): boolean => {
        const newErrors: Partial<
            Record<keyof AddDoctorFormData | `servicePrices_${number}_${keyof DoctorPrice}`, string>
        > = {};

        // Validate required fields
        validateRequiredFields(newErrors);

        // Validate email format
        if (
            formData.email &&
            !/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(formData.email)
        ) {
            newErrors.email = 'Định dạng email không hợp lệ';
        }

        // Password validation removed - backend will auto-generate secure password

        // Validate years of experience
        if (formData.yearsOfExperience < 0) {
            newErrors.yearsOfExperience = 'Số năm kinh nghiệm phải lớn hơn hoặc bằng 0';
        }

        // Validate languages
        if (formData.languageIds.length === 0) {
            newErrors.languageIds = 'Vui lòng chọn ít nhất một ngôn ngữ';
        }

        // Validate service prices
        validateServicePrices(newErrors);

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    }, [formData, validateRequiredFields, validateServicePrices]);

    const resetForm = useCallback(() => {
        const emptyFormData: AddDoctorFormData = {
            fullName: '',
            email: '',
            address: '',
            gender: Gender.MALE,
            bio: '',
            yearsOfExperience: 0,
            avatar: null,
            positionId: '',
            specialtyId: '',
            hospitalId: '',
            languageIds: [],
            servicePrices: [],
        };
        setFormData(emptyFormData);
        setErrors({});
    }, []);

    const prepareSubmitData = useCallback(() => {
        const doctorData = {
            fullName: formData.fullName,
            email: formData.email,
            address: formData.address,
            gender: formData.gender,
            bio: formData.bio,
            yearsOfExperience: formData.yearsOfExperience,
            positionId: formData.positionId,
            specialtyId: formData.specialtyId,
            hospitalId: formData.hospitalId,
            avatar: formData.avatar,
        };

        const doctorLanguages = formData.languageIds.map((languageId) => ({
            languageId,
        }));

        const doctorPrices: DoctorPrice[] = formData.servicePrices.map((price) => ({
            id: price.id,
            serviceTypeId: price.serviceTypeId,
            amount: price.amount,
        }));

        return { doctorData, doctorLanguages, doctorPrices };
    }, [formData]);

    return {
        formData,
        errors,
        setFormData,
        setErrors,
        handleInputChange,
        handleLanguageToggle,
        handleServicePriceChange,
        addServicePrice,
        removeServicePrice,
        handleFileChange,
        validateForm,
        resetForm,
        prepareSubmitData,
    };
};
