// Base request interface for email or phone validation
export interface EmailOrPhoneRequest {
    email?: string;
    phoneNumber?: string;
}

// Authentication Request DTOs
export interface LoginRequest extends EmailOrPhoneRequest {
    password: string;
}

// External Authentication Request DTOs
export interface GoogleLoginRequest {
    accessToken: string; // Changed from idToken to accessToken for modern OAuth flow
}

export interface FacebookLoginRequest {
    accessToken: string;
}

export interface ForgotPasswordRequest extends EmailOrPhoneRequest {
    deviceId?: string;
}

export interface ResetPasswordRequest {
    email: string;
    resetToken: string;
    newPassword: string;
    confirmNewPassword: string;
}

// Authentication Response DTOs
export interface AuthResponse {
    message: string;
    token?: string;
    requires2FA?: boolean;
    accountId?: string;
}

// Form validation types
export interface LoginFormData {
    email: string;
    password: string;
    rememberMe: boolean;
}

export interface ForgotPasswordFormData {
    email: string;
}

export interface ResetPasswordFormData {
    email: string;
    resetToken: string;
    newPassword: string;
    confirmNewPassword: string;
}

// Registration Request DTOs
export interface DoctorProfileRequest {
    positionId: string;
    specialtyId: string;
    hospitalId: string;
    bio: string;
    yearsOfExperience: number;
    languageIds?: string[];
    servicePrices?: Array<{
        serviceTypeId: string;
        amount: number;
    }>;
}

export interface RegisterDoctorRequest {
    email: string;
    fullName: string;
    gender: 'MALE' | 'FEMALE'; // String literal to match backend JSON with JsonStringEnumConverter
    address: string;
    doctorProfile: DoctorProfileRequest;
    // Note: Password is NOT required - will be auto-generated by backend and sent to doctor's email
}

// Auth state types
export interface AuthState {
    roles: string[];
    isAuthenticated: boolean;
    isLoading: boolean;
    error: string | null;
    emailConfirmed: boolean;
    phoneConfirmed: boolean;
    hasExternalProvider: boolean;
    accessToken: string | null; // Store access token for SignalR authentication
}

// Account Management types
export interface Account {
    accountId: string;
    email: string;
    fullName: string;
    avatarUrl?: string;
    phone?: string;
    address?: string;
    status: string;
    createdAt: string;
    isLocked: boolean;
}

export interface AccountManagementResponse {
    accounts: Account[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    totalPages: number;
}

// Two-Factor Authentication Request DTOs
export interface Enable2FARequest {
    verificationCode: string;
}

export interface Disable2FARequest {
    password: string;
}

export interface Verify2FARequest {
    accountId: string;
    verificationCode: string;
    rememberDevice?: boolean;
}

export interface RegenerateBackupCodesRequest {
    password: string;
}

// Two-Factor Authentication Response DTOs
export interface TwoFactorSetupData {
    secretKey: string;
    qrCodeUrl: string;
    manualEntryKey: string;
}

export interface Enable2FAResponse {
    success: boolean;
    message: string;
    backupCodes?: string[];
}

export interface Disable2FAResponse {
    success: boolean;
    message: string;
}

export interface RegenerateBackupCodesResponse {
    success: boolean;
    message: string;
    backupCodes?: string[];
}

export interface TwoFactorStatus {
    isEnabled: boolean;
    enabledAt?: string;
    remainingBackupCodes: number;
}
