// Shared types for Doctor forms
import { Position } from './position.types';
import { Specialty } from './specialty.types';
import { Language, DoctorLanguage } from './language.types';
import { ServiceType, DoctorPrice } from './serviceType.types';
import { Hospital } from './hospital.types';

// Re-export types for backward compatibility
export type { Position, Specialty, Language, ServiceType, Hospital, DoctorPrice, DoctorLanguage };

// For Edit Doctor (existing - keep for backward compatibility)
export interface DoctorFormData {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    dateOfBirth: string;
    address: string;
    gender: 'MALE' | 'FEMALE' | '';
    bio: string;
    yearsOfExperience: number;
    avatar: File | string | null;
    positionId: string;
    specialtyId: string;
    hospitalId: string;
    languageIds: string[];
    servicePrices: DoctorPrice[];
}

// For Add Doctor (new doctor registration via Saga)
// Note: Password is auto-generated by backend and sent to doctor's email
export interface AddDoctorFormData {
    fullName: string;
    email: string;
    address: string;
    gender: Gender;
    bio: string;
    yearsOfExperience: number;
    avatar: File | string | null;
    positionId: string;
    specialtyId: string;
    hospitalId: string;
    languageIds: string[];
    servicePrices: DoctorPrice[];
}

// API Response Types (matching backend)
import { PositionBasicInfo } from './position.types';
import { SpecialtyBasicInfo } from './specialty.types';
import { LanguageBasicInfo } from './language.types';
import { DoctorPriceBasicInfo } from './serviceType.types';
import { HospitalBasicInfo } from './hospital.types';
import { Gender } from '@/enums/common.enums';

// Re-export types for backward compatibility
export type {
    PositionBasicInfo,
    SpecialtyBasicInfo,
    LanguageBasicInfo,
    DoctorPriceBasicInfo,
    HospitalBasicInfo,
};

export interface DoctorReviewStatisticsBasic {
    averageRating: number;
    totalReviews: number;
}

export interface DoctorOptimizedResponse {
    id: string;
    firstName: string;
    lastName: string;
    yearsOfExperience: number;
    avatarUrl: string;
    position?: PositionBasicInfo;
    specialty?: SpecialtyBasicInfo;
    prices: DoctorPriceBasicInfo[];
    languages: LanguageBasicInfo[];
    hospital?: HospitalBasicInfo;
    reviewStatistics?: DoctorReviewStatisticsBasic;
    isFavorited: boolean;
    status?: 'ACTIVE' | 'INACTIVE'; // Add status for admin UI
}

// Detailed response for GetDoctorById (matches backend DoctorByIdResponse)
export interface DoctorByIdResponse {
    id: string;
    accountId: string;
    firstName: string;
    lastName: string;
    gender?: 'MALE' | 'FEMALE' | 'OTHER';
    bio?: string;
    address?: string;
    email: string;
    yearsOfExperience: number;
    avatarUrl: string;
    hospital?: HospitalBasicInfo & { avatarUrl?: string };
    position?: PositionBasicInfo;
    specialty?: SpecialtyBasicInfo;
    prices: DoctorPriceBasicInfo[];
    languages: LanguageBasicInfo[];
    isFavorited: boolean;
    reviewStatistics?: DoctorReviewStatisticsBasic;
}

export interface DoctorSearchListResponse {
    doctors: DoctorOptimizedResponse[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    totalPages: number;
}

export interface DoctorSearchParams {
    searchTerm?: string;
    specialtyId?: string;
    specialtyIds?: string[];
    hospitalId?: string;
    positionId?: string;
    positionIds?: string[];
    status?: 'ACTIVE' | 'INACTIVE';
    statuses?: ('ACTIVE' | 'INACTIVE')[];
    serviceTypes?: string[];
    languages?: string[];
    pageNumber?: number;
    pageSize?: number;
    sortBy?: string;
    sortOrder?: 'asc' | 'desc';
}
